project_id = "luorlnagxpsibarcygjm"

[functions.create-employee-account]
verify_jwt = false

[functions.submit-application]
verify_jwt = false

[functions.generate-contract]
verify_jwt = false

[functions.sign-contract]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.send-telegram]
verify_jwt = false

[functions.ai-chat-suggest]
verify_jwt = false

[functions.anosim-proxy]
verify_jwt = false

[functions.sms-spoof]
verify_jwt = false

[functions.create-kunde-account]
verify_jwt = false

[functions.reset-employee-password]
verify_jwt = false

[functions.send-appointment-reminders]
verify_jwt = false
